### ISSUE TITLE
parser gets internal stack error on verification

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/pandaPIparser#20]
```
$ pandaPIparser -V domain.hddl p01.hddl sample-ipyhopper-plan.hddl
pandaPIparser is configured as follows
  Colors in output: true
  Mode: plan verification
  Verbosity: 1
  Lenient mode: false
  Ignore given order: false
Could not set the stack size. setrlimit returned: -1
Plan verification result: false
```

This is on MacOS.

Looking into the code, it seems that setting the stack limit is only done in verify mode (at least, that's what I infer from the filename) [here](https://github.com/panda-planner-dev/pandaPIparser/blob/69016f1046ce221c14d82b7102de49a03e12c192/src/verify.cpp#L1302)

I note that the man page on MacOS says this:

> Only the super-user may raise the maximum limits.  Other users may only     alter rlim_cur within the range from 0 to rlim_max or (irreversibly)     lower rlim_max.

But there is no check in the code to make sure that the `rl` value is less than `rlim_max`.  I will add such a check and see if this fixes the problem.

**Comment by galvusdamor** [comment]
Ack. This seems only to be a problem under MacOS as this works under linux. I'll accept the PR.
