### ISSUE TITLE
Revised Makefile

### ISSUE THREAD

**Issue by rpgoldman** [panda-planner-dev/pandaPIparser#7]
Here's a revised version of the `makefile` (renamed to `makefile.txt`, so GitHub allows me to upload it) that I have used on MacOS that might be helpful.  It has two changes in it:

1. I try to detect MacOS and, if I do, remove the static linking flags automatically, instead of requiring the user to edit the `makefile`.
2. I replaced the `CC` variable with `CXX` which is what GNU Make specifies for a C++ compiler (instead of a standard C compiler).

[makefile.txt](https://github.com/panda-planner-dev/pandaPIparser/files/6273116/makefile.txt)

**Comment by panda-planner-dev** [comment]
Hi Robert!

Thank you very, very much for this fix! I have just added it to the master branch.

Kind regards,
Gregor
