### ISSUE TITLE
pandaPIparser not running on Windows 10 WSL/Ubuntu

### ISSUE THREAD

**Issue by 19CMB94** [panda-planner-dev/pandaPIparser#9]
Hello,

I just wanted to let you know that the current version of pandaPIparser (cloned on July 14, 15:30) does not verify plans that have been verified correctly by former versions of pandaPIparser on the Windows Subsystem for Linux (running Ubuntu 20.04.2 LTS; Windows version: 10.0.19041.1083). Running pandaPIparser with the Barman-BDI domain on instance pfile01.hddl from [https://github.com/panda-planner-dev/ipc2020-domains/tree/master/total-order/Barman-BDI](https://github.com/panda-planner-dev/ipc2020-domains/tree/master/total-order/Barman-BDI) and the solution attached I get the following result:

pandaPIparser is configured as follows
  Colors in output: true
  Mode: plan verification
  Verbosity: 0
  Lenient mode: false
  Ignore given order: false
Could not set the stack size. setrlimit returned: -1
Plan verification result: false

However, pandaPIparser works fine on the system of a friend of mine who runs native Ubuntu. Unfortunately, I have no access to a native Linux system where I have the permission to install gengetopt. Older versions of pandaPIparser work just fine.

Best regards
[plan_correct.txt](https://github.com/panda-planner-dev/pandaPIparser/files/6816739/plan_correct.txt)

**Comment by galvusdamor** [comment]
Thanks for reporting this issue. I don't have a Windows machine available to test this problem, but you should be able to (locally) fix the issue by commenting out line 1294-1308 in src/verify.cpp
We are increasing the stack limit here as the default stack limit might not be enough for exceptionally long (more than ~1.000.000 actions iirc) plans.

I'll try to to work on a means to do this correctly under Windows.

**Comment by 19CMB94** [comment]
Thank you, that fixed the issue. The parser works now as expected (at least for me). :)
